### ISSUE TITLE
Compose automation with Markdown

### ISSUE THREAD

**Issue by samspot** [jneug/osx-script-stuff#1]
I saw you were doing some airmail scripting, and I was wondering if you would know how to have applescript click the "Markdown" feature in the compose window.  In return I'll share my script that allows me to send a vim buffer to a new email:

```
#!/bin/bash

# in vim do:  :w !~/airscript.sh

osascript 3<&0 <<'APPLESCRIPT'
on run argv
    set stdin to do shell script "cat 0<&3"
    tell application "Airmail 3" to activate
    tell application "System Events"
        tell process "Airmail 3" to click menu item "New Message" of menu "File" of menu bar 1
        delay .4
		-- Below does not work:
		-- tell process "Airmail 3" to click link "Markdown" of window 1 of window 1
        keystroke tab
        keystroke tab
        keystroke tab
        keystroke tab
        keystroke tab
        keystroke stdin
    end tell
end run
APPLESCRIPT

#osascript 3<&0 airmail.as

```

**Comment by jneug** [comment]
Don't know a way to do this by script, but you could simply activate the markdown editor as a default in the compose settings of your mail account in AirMail (`settings -> accounts -> %you account% -> compose -> default editor`).

**Comment by samspot** [comment]
Ah ok thanks, i did look for that in normal settings, but I didn't think to look under accounts - thanks!
