### ISSUE TITLE
Save attachments in Airmail 

### ISSUE THREAD

**Issue by crjstobal** [jneug/osx-script-stuff#2]
The script only downloads the first attachment and ignores the rest.

Is there any way of changing this behavior? :)

**Comment by jneug** [comment]
Try this version and let me know if it works:

```applescript
(*
name:           Save attachments
apps:            Airmail 3
description:    Use as a script in Airmail rules to save attachments to the selected folder.
parameters:
    DOWNLOADS:      Folder to save attachments to
compile:        false
*)
property DOWNLOADS : "~/Downloads"

on processMessage(theMessage)
	try
		tell application "Airmail 3"
			repeat with theAttach in mail attachment of theMessage
				--set theAttach to filename of first mail attachment of theMessage
				set thePDF to quoted form of POSIX path of filename of theAttach
				do shell script "cp " & thePDF & " " & DOWNLOADS
			end repeat
		end tell
	end try
end processMessage
```

**Comment by crjstobal** [comment]
Didn't work for me :(

What I've done is create several scripts changing 

`set theAttach to filename of first mail attachment of theMessage`

For "second", "third" and so, and then execute all of them, but I think it has to be a better solution like the one you coded above :/

**Comment by jneug** [comment]
I just comited a new version of the script that should save all attachments for an email.

**Comment by crjstobal** [comment]
Thanks Jonas! It works like a charm :)

**Comment by taxman11** [comment]
I am running 10.12.5 and copied the code from your script exactly as is and no attachments get moved to the Downloads folder. Any thoughts?

**Comment by jneug** [comment]
@taxman11 Try the new version I uploaded for this issue: #3

**Comment by taxman11** [comment]
Still does not work for me. Using version 3.2.7 of Airmail.

**Comment by jneug** [comment]
Are you sure the mail rule is set up correct? At the bottom of the rules window is a "Preview" button. See, if there are mails with attachments found. Then you can apply the rule to the matched mails to see if the script is working.

**Comment by taxman11** [comment]
Positive. I click the Preview button and it lists the emails the rule applies to. In my case it is emails in a particular account sent to a specific email address then run the AppleScript you created. I click the Preview button which then shows the emails the rule applies to and when I click Apply to previous messages nothing happens.

Sent from my iPhone

On May 21, 2017, at 10:12 AM, Jonas Neugebauer <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you sure the mail rule is set up correct? At the bottom of the rules window is a "Preview" button. See, if there are mails with attachments found. Then you can apply the rule to the matched mails to see if the script is working.

**Comment by jneug** [comment]
Open the applescript editor application, copy and paste the script code into a new document and append these two lines:

```applescript
tell application "Airmail 3" to set theMessage to selected message
my processMessage(theMessage)
```

Open AirMail, select the message with the attachment and run the script in the editor. Does it work that way?

**Comment by taxman11** [comment]
Forgive my ignorance but where exactly should I add this additional code you posted? 

Should I add it immediately after the end processMessage?

And how do I select a message in Airmail that the script should apply to and run that in the script editor?

**Comment by jneug** [comment]
The full script would look like this

```applescript
property DOWNLOADS : "~/Downloads"

on processMessage(theMessage)
	try
		tell application "Airmail 3"
			repeat with anAttach in mail attachments of theMessage
				set aFilename to filename of anAttach
				set aFile to quoted form of POSIX path of aFilename
				do shell script "cp " & aFile & " " & DOWNLOADS
			end repeat
		end tell
	end try
end processMessage

tell application "Airmail 3" to set theMessage to selected message
my processMessage(theMessage)
```

**Comment by taxman11** [comment]
Thanks so much! That appears to have done the trick. If it is not too much trouble, could you tell me what the additional code would be to then move the copied files from the ~/Downloads folder to a folder named “Temp” that is located on the Desktop?

**Comment by jneug** [comment]
You can change the path at the top of the script:

```applescript
property DOWNLOADS : "~/Desktop/Temp"
```

But you shouldn't use this version in any Airmail rule. If it is working by manually running the script from the script editor the problem seems to be how you setup your rule in Airmail.

**Comment by taxman11** [comment]
I never ran the script in the Script editor. It now seems to be working fine within Airmail itself after adding the last bit of code you supplied.

It is my understanding that with the new “sandboxing” restrictions of Sierra that you can only run scripts to copy files to the Download folder.



On May 22, 2017 at 3:01:59 PM, Jonas Neugebauer (notifications@github.com<mailto:notifications@github.com>) wrote:

You can change the path at the top of the script:

property DOWNLOADS : "~/Desktop/Temp"

But you shouldn't use this version in any Airmail rule. If it is working by manually running the script from the script editor the problem seems to be how you setup your rule in Airmail.

**Comment by taxman11** [comment]
Was wondering if you had a chance to respond to my message a couple of days ago about the Downloads folder. Just out of curiosity, I tried changing the property Downloads as you mentioned and the attachments did not copy so it appears the "sandboxing" issue I have read about may in fact be true.

On another note, using the code as is, I have an issue when I receive multiple emails in close proximity that both contain a file, for example called Doc - 05-24-17 -2-39 PM.pdf. In that case, only one of the files makes it to the destination folder since they have the same name. Is it possible to add some code to append a digit or something else to the duplicate filename so both files are copied?

Thanks

**Comment by crjstobal** [comment]
If you want to copy attachments to another folder just try Hazel.

___
Javier Cristóbal

El 22 de mayo de 2017 a las 22:19:40, taxman11 (notifications@github.com) escribió:

I never ran the script in the Script editor. It now seems to be working fine within Airmail itself after adding the last bit of code you supplied.

It is my understanding that with the new “sandboxing” restrictions of Sierra that you can only run scripts to copy files to the Download folder.



On May 22, 2017 at 3:01:59 PM, Jonas Neugebauer (notifications@github.com<mailto:notifications@github.com>) wrote:

You can change the path at the top of the script:

property DOWNLOADS : "~/Desktop/Temp"

But you shouldn't use this version in any Airmail rule. If it is working by manually running the script from the script editor the problem seems to be how you setup your rule in Airmail.
