### ISSUE TITLE
Mail Attachments

### ISSUE THREAD

**Issue by wazime** [jneug/osx-script-stuff#4]
I was trying to use your script but it doesn't work in MacOs High Sierra. Do you have a script that works. I am trying to get my PDF attachments to download when the new mail arrives. I have created the rule, just looking for a working AppleScript.

**Comment by admin-teametry** [comment]
For me the same. It would be nice to have a working solution in High Sierra :-)

Thanks

**Comment by jneug** [comment]
I updated the script. Hope it works now.

**Comment by wazime** [comment]
It looks like you changed the AirMail script, or did you also change the one for Apple Mail. That was the one I was referring to.
